# Generated by Django 4.0.4 on 2022-04-23 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=100, verbose_name='name of book')),
                ('author', models.TextField(max_length=100, verbose_name='the author')),
                ('created', models.DateField()),
                ('stock_count', models.PositiveSmallIntegerField(verbose_name='stock count')),
                ('prize', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='prize of book')),
            ],
            options={
                'db_table': 'Book',
            },
        ),
    ]
