# Generated by Django 4.0.4 on 2022-04-23 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.TextField(default='anonim', max_length=100, verbose_name='the author'),
        ),
    ]
